---
- hosts: localhost
  connection: local
  become_user: benjaminshafii
  vars:
    username: benjaminshafii
    packages:
      - ack
      - adobe-source-code-pro-fonts
      - arandr
      - calibre
      - chromium
      - clang
      - compton
      - docker
      - dunst
      - docker-compose
      - firefox-developer
      - i3-gaps
      - i3lock
      - nodejs
      - openvpn
      - pavucontrol
      - playerctl
      - polybar-git
      - rofi
      - scrot
      - slack-desktop
      - synergy
      - termite
      - tree
      - ttf-fira-mono
      - ttf-font-awesome
      - ttf-monaco
      - ttf-ms-fonts
      - vlc
      - xorg-xbacklight

    dotfiles:
      - config/Xresources
      - config/compton
      - config/dunst
      - config/i3
      - config/polybar
      - config/rofi
      - config/termite
      - gitconfig
      - gitignore_global
      - vimrc
      - xclip
      - xinitrc
      - zshrc

  tasks:
    - name: Create dotfile symlinks
      file:
        src: /home/benjaminshafii/dotfiles/{{ item }}
        dest: /home/benjaminshafii/.{{ item }}
        state: link
        force: yes
      with_items: "{{ dotfiles }}"
      tags:
        - dotfiles

    - name: Install "{{ item }}"
      aur: name={{ item }}
      with_items: "{{ packages }}"
      tags:
        - install

    - name: Copy secrets
      copy:
        src: /home/benjaminshafii/ansible-personal/toolbox.zsh
        dest: /home/benjaminshafii/.config/toolbox.zsh
        decrypt: yes
        force: yes
      tags:
        - secrets

    - name: Create Docker groups
      group:
        name: docker
        state: present
      tags:
        - docker

    - name: Add Docker to sudoers
      user:
        append: yes
        group: docker
        name: "{{ username }}"
      become: true
      tags:
        - docker


