---
- hosts: localhost
  connection: local
  become_user: benjaminshafii
  vars:
    packages:
      - calibre
      - chromium
      - firefox-developer
      - polybar-git
      - spotifyd
      - docker
      - docker-compose
      - ack
      - i3lock
      - i3-gaps
      - nodejs
      - playerctl
      - rofi
      - slack-desktop
      - synergy
      - tree
      - ttf-fira-mono
      - ttf-monaco
      - ttf-ms-fonts
      - vlc
      - adobe-source-code-pro-fonts
      - compton
      - clang
      - arandr
      - ttf-font-awesome
      - termite

    dotfiles:
      - gitconfig
      - gitignore_global
      - vimrc
      - xinitrc
      - zshrc
      - config/compton
      - config/dunst
      - config/rofi
      - config/polybar
      - config/i3
      - config/Xresources
      - config/termite

  tasks:
    - name: Create dotfile symlinks
      file:
        src: /home/benjaminshafii/dotfiles/{{ item }}
        dest: /home/benjaminshafii/.{{ item }}
        state: link
        force: yes
      with_items: "{{ dotfiles }}"
      tags:
        - dotfiles

    - name: Install "{{ item }}"
      aur: name={{ item }}
      with_items: "{{ packages }}"
      tags:
        - install




